"""Part 17 — transformer sentence embeddings (Unit V: word embeddings, attention, transformers).

Model: sentence-transformers/all-MiniLM-L6-v2 (6 transformer layers with self-attention, 384-dim output,
mean pooling, unit length). Pretrained, used as a fixed encoder: no prices involved, no fine-tuning.
4 CPU threads (memory / worker cap).

1. Embeddings vs TF-IDF on word pairs: same meaning, different words.
2. Similar-items search (as part 11): FAISS 10 nearest training neighbours, median price -> test R².
   LSA (TF-IDF + SVD, part 11) vs MiniLM.
3. Do the embeddings add to the best model (S12-img)? PCA fitted on training rows; grouped 5-fold CV
   picks 0 / 32 / 64 / 128 components. Chosen setting -> stage S12-img-st in evaluate_stage.py.
Usage: python scripts/part17_sentence_embeddings.py encode   then   ... evaluate
Outputs: data/features/sentence_pca.csv.gz, reports/models/part17_sentence.json, part17_run.log.
The raw 384-dim embeddings (data/features/sentence_emb_minilm.npy, ~57 MB) are git-ignored and
can be regenerated by this script (the model is deterministic).
"""
import os, sys, json, time, numpy as np, pandas as pd
# PyTorch and FAISS each ship an OpenMP runtime; on macOS loading both in one process crashed (exit 139).
# So the script runs in two separate steps:  encode  (PyTorch only)  then  evaluate  (FAISS + sklearn only).
STEP = sys.argv[1]
N = 4
MODEL = "sentence-transformers/all-MiniLM-L6-v2"
d = pd.read_csv("data/final/handicraft_clean.csv.gz", keep_default_na=False)
sa = pd.read_csv("data/splits/split_assignment.csv").set_index("image_file")
d["split"], d["family"] = d.image_file.map(sa.split), d.image_file.map(sa.family)
text = (d.product_title + ". " + d.product_description).tolist()
out = {"model": MODEL}
if STEP == "encode":
    import torch
    from sentence_transformers import SentenceTransformer
    from sklearn.feature_extraction.text import TfidfVectorizer
    torch.set_num_threads(4)
    st = SentenceTransformer(MODEL, device="cpu")
    out.update(dims=st.get_embedding_dimension(), max_tokens=st.max_seq_length)

    path = "data/features/sentence_emb_minilm.npy"
    if os.path.exists(path):
        E = np.load(path)
    else:
        t = time.time()
        E = st.encode(text, batch_size=64, normalize_embeddings=True, show_progress_bar=False).astype(np.float32)
        np.save(path, E); out["encode_seconds"] = round(time.time() - t, 1)
    print("embeddings", E.shape, out.get("encode_seconds"), flush=True)

    # 1 — word pairs: learned embeddings vs TF-IDF (TF-IDF gives 0 when no word is shared)
    pairs = [("dupatta", "stole"), ("saree", "sari"), ("keychain", "key ring"), ("earrings", "jhumka"),
             ("handwoven", "handloom"), ("silk saree", "cotton saree"), ("saree", "keychain"), ("necklace", "cushion cover")]
    tf = TfidfVectorizer().fit([w for p in pairs for w in p])
    rows = []
    for a, b in pairs:
        ea, eb = st.encode([a, b], normalize_embeddings=True)
        ta, tb = tf.transform([a]).toarray()[0], tf.transform([b]).toarray()[0]
        tcos = float(ta @ tb / (np.linalg.norm(ta) * np.linalg.norm(tb) + 1e-12))
        rows.append(dict(a=a, b=b, minilm_cosine=round(float(ea @ eb), 3), tfidf_cosine=round(tcos, 3)))
    out["word_pairs"] = rows
    print(pd.DataFrame(rows).to_string(index=False), flush=True)

    json.dump(out, open("reports/models/part17_encode.json", "w"), indent=1)
    sys.exit(0)

out = json.load(open("reports/models/part17_encode.json"))
E = np.load("data/features/sentence_emb_minilm.npy")
import faiss
from sklearn.decomposition import PCA
from sklearn.linear_model import Ridge
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GroupKFold, cross_val_predict
from sklearn.metrics import r2_score, mean_absolute_error

# 2 — similar-items search: LSA (part 11 representation) vs MiniLM, same FAISS exact inner-product index
tr_m = (d.split == "train").values
tr, te = d[tr_m].reset_index(drop=True), d[~tr_m].reset_index(drop=True)
from features import load, dense
ftr, fte, kgc = load()
_, _, Ltr, Lte = dense(ftr, fte, kgc)                      # LSA vectors, same rows as part 11
def knn_r2(Xtr, Xte, ptr, pte, k=10):
    idx = faiss.IndexFlatIP(Xtr.shape[1]); idx.add(np.ascontiguousarray(Xtr, dtype=np.float32))
    sims, nn = idx.search(np.ascontiguousarray(Xte, dtype=np.float32), k)
    pred = np.median(ptr[nn], axis=1)
    return dict(r2=round(r2_score(pte, pred), 4), mae=round(mean_absolute_error(pte, pred), 1),
                mean_top10_similarity=round(float(sims.mean()), 3))
out["retrieval_10nn"] = {
    "LSA (TF-IDF + SVD 100, part 11)": knn_r2(Ltr, Lte, ftr.price.values, fte.price.values),
    "MiniLM transformer (384)": knn_r2(E[tr_m], E[~tr_m], tr.price.values, te.price.values)}
print(json.dumps(out["retrieval_10nn"], indent=1), flush=True)

# 3 — added to the best model: PCA on training rows, components chosen by grouped CV
pca = PCA(n_components=128, random_state=42).fit(E[tr_m])
Z = pca.transform(E)
out["pca_explained_variance"] = {k: round(float(pca.explained_variance_ratio_[:k].sum()), 3) for k in (32, 64, 128)}
pd.DataFrame(Z.astype(np.float32), columns=[f"st_pc{i + 1}" for i in range(128)]).round(5).assign(
    image_file=d.image_file.values).to_csv("data/features/sentence_pca.csv.gz", index=False)

ns = {}; exec(open("scripts/part8b_ablation_tuning.py").read().split("# --- ablation")[0], ns)   # S12 feature builder
kimg = json.load(open("reports/models/part13_images.json"))["s12_plus_images_cv"]["chosen_components"]
imgc = [f"img_pc{i + 1}" for i in range(kimg)]
base = ns["d"].merge(pd.read_csv("data/features/image_pca.csv.gz", usecols=["image_file"] + imgc), on="image_file")
base = base.merge(pd.read_csv("data/features/sentence_pca.csv.gz"), on="image_file")
GROUPS, make_pre = ns["GROUPS"], ns["make_pre"]
GROUPS["image (SqueezeNet PCA)"] = ("num", imgc)
btr = base[base.split == "train"].reset_index(drop=True)
cv = list(GroupKFold(5).split(btr, groups=btr.family))
res = {}
for k in (0, 32, 64, 128):
    GROUPS["sentence embedding (MiniLM PCA)"] = ("num", [f"st_pc{i + 1}" for i in range(k)])
    groups = [g for g in GROUPS if g != "sentence embedding (MiniLM PCA)" or k > 0]
    m = Pipeline([("pre", make_pre(groups, max_features=20000, min_df=2)), ("ridge", Ridge(alpha=1.0))])
    oof = np.exp(cross_val_predict(m, btr, np.log(btr.price.values), cv=cv, n_jobs=N))
    res[k] = dict(r2=round(r2_score(btr.price, oof), 4), mae=round(mean_absolute_error(btr.price, oof), 1))
    print("components", k, res[k], flush=True)
out["s12img_plus_sentence_cv"] = {"cv_by_components": res, "chosen_components": max(res, key=lambda k: res[k]["r2"])}
json.dump(out, open("reports/models/part17_sentence.json", "w"), indent=1)
print(json.dumps(out["s12img_plus_sentence_cv"], indent=1))
